_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.7
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
batch_size:
    value: 1
max_length:
    value: 128
model_id:
    value: microsoft/phi-2
name:
    value: Phi-2 4bit
quantization:
    value: 4bit
